Dg update manual testing
AY1920S2-CS2103T-W12-1/main pull request #116
Opened 2020-02-28 08:16 UTC by Amoscheong97

2020-02-29 02:01 UTC, Exeexe93 approved these changes
Look good to merge.

2020-02-29 14:59 UTC, khsc96 requested changes
Minor changes, standardisation issue other than that goodjob!

2020-02-29 14:59 UTC, khsc96 commented on docs/DeveloperGuide.adoc
> +.. Edit Command Syntax: `edit` `*TRANSACTION ID*` `*FIELD*` `*NEW VALUE*`
I think we should standardise the name of the field either with _ or without.

2020-03-03 10:04 UTC, khsc96 requested changes
Please have a look at the comments i've given and change some whitespace to underscore accordingly thankyou!

2020-03-03 10:04 UTC, khsc96 commented on docs/DeveloperGuide.adoc
> +.. Test case: `list` `ANY WORD OTHER THAN UNDONE AND DONE` +
separate white space by underscore thanks!

2020-03-03 10:04 UTC, khsc96 commented on docs/DeveloperGuide.adoc
> +.. Test case: `delete` `ANY INDEX NOT FOUND IN LIST` +
separate whitespace by underscore! or can simply put INVALID_INDEX

2020-03-03 10:04 UTC, khsc96 commented on docs/DeveloperGuide.adoc
> +.. Edit command format: `edit` `INDEX` `PREFIX/NEW VALUE`
NEW_VALUE, thank you!

2020-03-03 10:04 UTC, khsc96 commented on docs/DeveloperGuide.adoc
> +.. Test case: `undo` `ANY OTHER WORD` +
Perhaps can use INVALID_SYNTAX instead

2020-03-03 10:21 UTC, khsc96 approved these changes
LGTM, Thanks!

2020-03-03 10:22 UTC, merged