Show Command and major UI change
AY1920S2-CS2103T-W12-1/main pull request #318
Opened 2020-04-08 15:28 UTC by Amoscheong97

Things done:
1) Refactor Show Command
2) Change UI : OrderCard, ReturnCard (Add icons) and add Tabs for statistics and list of orders.
3) Add authors for my classes
4) Edit UG and DG for Show Command
5) Add Test cases
6) Change regex for Cash On Delivery to only allow a value of less than $10,000,000,000,000
7) Edit isSameParcel method to only check for same Transaction ID

2020-04-08 19:34 UTC, khsc96 requested changes
Overall goodjob! minor changes like the way you type tag author need to change i don't think u can mix it in javadoc cause reposense won't sense until.

2020-04-08 19:34 UTC, khsc96 commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +                isCommandSuccessful = true;
Probably can SLAP abit harder here, other than that looks good!

2020-04-08 19:34 UTC, khsc96 commented on src/main/java/seedu/address/logic/commands/ShowCommand.java
> +                }
Maybe here can drag out as a method? something like
`checkValidInput(arrOfDate)`

2020-04-08 19:34 UTC, khsc96 commented on src/main/java/seedu/address/logic/parser/InsertCommandParser.java
> + * @author Amoscheong97
I think the @author right you got to put above the javadoc or below, you can have a look at either mine or jeremy's classs you need to use the 
`//@@author Amoscheong97` something like this

2020-04-09 09:49 UTC, khsc96 approved these changes
NAISE USE OF SLAP, CODE IS OBEDIENT NOW! Help to do the merge conflict than it's LGTM! thanks

2020-04-09 10:10 UTC, JeremyLoh approved these changes
LGTM! Thanks!

2020-04-09 10:10 UTC, Exeexe93 approved these changes
LGTM

2020-04-09 10:10 UTC, merged